using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    private CharacterController characterController;//CharacterControllerï¿½Ïï¿½
    private Animator animator;                      //Animatorï¿½Ïï¿½
    private Vector3 vector;                         //ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½ğ“®‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ß‚ï¿½Vector3ï¿½Ïï¿½

    //public Rigidbody rb;
    public float forwordpower = 0.01f;//ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½Ì‹ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½Ì—ï¿½
    float widthpower = 0.2f;//ï¿½ï¿½ï¿½Ú“ï¿½ï¿½Ì•ï¿½
    float jumpforce = 4.0f;//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½ï¿½ï¿½Ì—Í‰ï¿½ï¿½ï¿½
    public bool isGround = true;//ï¿½nï¿½Ê‚É‚Â‚ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½
    public int playerHP=10;//ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½HP

    float times=1.0001f;//ï¿½ï¿½ï¿½Xï¿½É‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½é‚½ï¿½ß‚ï¿½

    public PlayerCollision playerCollision;
    public Blinkinger blinkinger;

    //public bool isBlink = false;//ï¿½_ï¿½Å‚ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½
    public bool isClear = false;//ï¿½Nï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½
    public bool isOver = false;//ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½[ï¿½oï¿½[ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½Ç‚ï¿½ï¿½ï¿½

    public Vector3 playerpos;//ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®ç¾åœ¨åœ°ä¿å­˜ç”¨

    // Start is called before the first frame update
    void Start()
    {
        //rb = GetComponent<Rigidbody>();
        characterController = GetComponent<CharacterController>();
        animator = GetComponent<Animator>();
        isClear = false;
        isOver = false;
}

    // Update is called once per frame
    void Update()//å…¥åŠ›ã€åˆ¤å®šã¯ã“ã£ã¡ã§è¡Œã†ã“ã¨
    {
        if (StartButtonSC.isStart)
        {

            if (Input.GetKeyDown(KeyCode.Space) && -15.0f < transform.position.x && !isClear)//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÉˆÚ“ï¿½
            {
                //transform.position -= widthpower * transform.right;
                characterController.Move(this.gameObject.transform.right * -1 * widthpower);
            }
            if ((Input.GetMouseButtonDown(0) || Input.GetMouseButtonDown(1)) && transform.position.x < 15.0f && !isClear)//ï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½ÉˆÚ“ï¿½
            {
                //transform.position += widthpower * transform.right;
                characterController.Move(this.gameObject.transform.right * widthpower);
            }

            if (Input.GetMouseButton(2) && Input.GetKey(KeyCode.Return) && isGround && !isClear)//ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½v
            {
                //transform.position += jumpforce * transform.up;
                vector.y = jumpforce;
                animator.SetBool("Jump", true);
                isGround = false;
            }
            else
            {
                //ï¿½dï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
                vector.y += Physics.gravity.y * Time.deltaTime;
            }



            

            

            //transform.position += forwordpower * transform.forward;
            //rb.velocity = Vector3.forward * 2.0f;//ï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½É‚QNï¿½Ì—Í‚ÅˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½
        }
        playerpos = this.transform.position;
    }
    private void FixedUpdate()//å®Ÿéš›ã«å‹•ã‹ã™ã¨ãã¯ã“ã£ã¡ã®é–¢æ•°ã‚’ä½¿ã†
    {
        Transform transform = this.transform;           //transformã‚’ä¿å­˜ã™ã‚‹
        Vector3 localAngle = transform.localEulerAngles;//ç¾åœ¨ã®ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®æ–¹å‘ã‚’ã¨ã£ã¦ãã‚‹
        localAngle.y = 0.0f;                            //Yè»¸å›è»¢ã‚’0ã«å¼·åˆ¶çš„ã«å¤‰ãˆã‚‹
        transform.localEulerAngles = localAngle;        //å®Ÿéš›ã«ã“ã“ã§å›è»¢ã‚’å¤‰ãˆã‚‹

        if (StartButtonSC.isStart)
        {
            characterController.Move(this.gameObject.transform.forward * forwordpower);
            animator.SetBool("Run", true);//ã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³ã‚’åŸºæœ¬ã¯Runã«ã™ã‚‹

            //å‰é€²é‹å‹•
            characterController.Move(vector * Time.deltaTime);

            if (isClear)
            {
                forwordpower = 0.0f;//å‰é€²é‹å‹•åœæ­¢
                localAngle.y = 180.0f;//ã‚«ãƒ¡ãƒ©å´ã‚’å‘ãã‚ˆã†ã«å›è»¢
                transform.localEulerAngles = localAngle;//å®Ÿéš›ã«ã“ã“ã§å›è»¢ã‚’å¤‰ãˆã‚‹
                animator.SetBool("Dance", true);//ã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³ã‚’Danceã«å¤‰æ›´
            }
            if(isOver)
            {
                forwordpower = 0.0f;//å‰é€²é‹å‹•åœæ­¢
                animator.SetBool("Death", true);//ã‚¢ãƒ‹ãƒ¡ãƒ¼ã‚·ãƒ§ãƒ³ã‚’Danceã«å¤‰æ›´
            }

            forwordpower *= times;
        }
    }

    private void OnCollisionExit(Collision collision)//åœ°é¢ã‹ã‚‰é›¢ã‚ŒãŸã¨ãå‘¼ã³å‡ºã•ã‚Œã‚‹
    {
        isGround = false;
        Debug.Log("isground");

    }

    private void OnTriggerEnter(Collider other)//Triggerã¨ã®æ¥è§¦åˆ¤å®š
    {
        
        playerCollision.PCollision(other);
        //isBlink = true;
        blinkinger._time = 0.0f;

    }
    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.tag == "Ground")//åœ°é¢ã¨æ¥è§¦ã—ãŸæ™‚å‘¼ã³å‡ºã•ã‚Œã‚‹
        {
            isGround = true;
            animator.SetBool("Jump", false);
            Debug.Log("Ground");
        }
    }
}
